package june0630;
import java.util.Scanner;
public class c_10_inputException {

	public static void main(String[] args) {
		Scanner scan = new Scanner(System.in);
		try {
			System.out.print("첫수 입력(정수):");
			int num1 = scan.nextInt();
			System.out.print("피젯수 입력(정수):");
			int num2 = scan.nextInt();
			int mog = num2 / num1;
			int na = num2 % num1;
			
			System.out.println(num2 + "를" + num1 + "으로 나눈 몫" + mog);
			System.out.println(num2 + "를" + num1 + "으로 나눈 나머지" + na);
		}
		catch(Exception e) {
			System.out.println("Exception 발생!");
			System.out.println("예외 정보:" + e.getMessage());
			e.printStackTrace();
		}
		System.out.println("main 메소드가 종료됩니다.");

	}

}
